-- Inserir times de Pernambuco que faltaram (1-B e demais categorias)
-- pais_id = 26 (Brasil), estado_id = 17 (Pernambuco)

INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- 1-B
('1º de Maio', 'https://escudosfc.com.br/images/primeirodemaio_pe.png', 26, 17),
('AFASA', 'https://escudosfc.com.br/images/afasa_pe.png', 26, 17),
('Afogadense', 'https://escudosfc.com.br/images/afogadense_pe.jpg', 26, 17),
('AGA', 'https://escudosfc.com.br/images/aga_pe.png', 26, 17),
('Alegriense', 'https://escudosfc.com.br/images/alegria_pe.jpg', 26, 17),
('Altinho', 'https://escudosfc.com.br/images/altinho_pe.jpg', 26, 17),
('Aluminio', 'https://escudosfc.com.br/images/aluminio_pe.png', 26, 17),
('América (Sertânia)', 'https://escudosfc.com.br/images/america_sertania_pe.png', 26, 17),
('Arapirina', 'https://escudosfc.com.br/images/arapina_pe.png', 26, 17),
('Arapirina SC', 'https://escudosfc.com.br/images/araripina_sc_pe.png', 26, 17),
('Arcoverde', 'https://escudosfc.com.br/images/arcoverde_pe.jpg', 26, 17),
('Arruda', 'https://escudosfc.com.br/images/pe_arruda.png', 26, 17),
('Arsenal Noronhense', 'https://escudosfc.com.br/images/arsenal_fn.png', 26, 17),
('ASA', 'https://escudosfc.com.br/images/asa_pe.png', 26, 17),
('Asa Branca', 'https://escudosfc.com.br/images/asa_branca_pe.png', 26, 17),
('Asas', 'https://escudosfc.com.br/images/pe_asas.png', 26, 17),
('Ateniense', 'https://escudosfc.com.br/images/ateniense_pe.png', 26, 17),
('Atlântico', 'https://escudosfc.com.br/images/atlantico_fn.png', 26, 17),
('Atlético de Camaragibe', 'https://escudosfc.com.br/images/ateletico_camaragibe_pe.png', 26, 17),
('Atlético Caruaru', 'https://escudosfc.com.br/images/atl_caruaru_pe.jpg', 26, 17),
('Atlético Goiana', 'https://escudosfc.com.br/images/atletic_go_pe.png', 26, 17),
('Atlético Pernambucano', 'https://escudosfc.com.br/images/atletico_pernambucano.png', 26, 17),
('Atlético Vicência', 'https://escudosfc.com.br/images/vicencia_pe.gif', 26, 17),
('Auto Esporte', 'https://escudosfc.com.br/images/pe_autoesporte.png', 26, 17),
('Barcelona', 'https://escudosfc.com.br/images/barcelona_pe.png', 26, 17),
('Barreiros AE', 'https://escudosfc.com.br/images/barreiros_ae_pe.png', 26, 17),
('Barreiros FC', 'https://escudosfc.com.br/images/barreiros_pe.png', 26, 17),
('Buíque', 'https://escudosfc.com.br/images/buique_pe.png', 26, 17),
-- C
('Cabense', 'https://escudosfc.com.br/images/cabense.jpg', 26, 17),
('Cacique', 'https://escudosfc.com.br/images/pe_cacique.jpg', 26, 17),
('Caiano CS', 'https://escudosfc.com.br/images/caiano_sc_pe.jpg', 26, 17),
('Caiano EC', 'https://escudosfc.com.br/images/caiano_ec.png', 26, 17),
('Camela', 'https://escudosfc.com.br/images/cemela_pe.png', 26, 17),
('Carpina', 'https://escudosfc.com.br/images/carpina_pe.jpg', 26, 17),
('Carpinense', 'https://escudosfc.com.br/images/carpinense_pe.jpg', 26, 17),
('Caruaru EC', 'https://escudosfc.com.br/images/pe_caruaru_ec.png', 26, 17),
('Casa Caiada', 'https://escudosfc.com.br/images/caca_caiada_pe.jpg', 26, 17),
('Casa Forte', 'https://escudosfc.com.br/images/pe_casaforte.jpg', 26, 17),
('Caxangá', 'https://escudosfc.com.br/images/caxanga_pe.png', 26, 17),
('Central Barreiros', 'https://escudosfc.com.br/images/central_barreiros_pe.png', 26, 17),
('Centro Esportivo', 'https://escudosfc.com.br/images/centro_esp_pe.png', 26, 17),
('Centro Sportivo Pernambucano', 'https://escudosfc.com.br/images/pe_csp.jpg', 26, 17),
('Chã Grande', 'https://escudosfc.com.br/images/chagrande_pe.png', 26, 17),
('Chelsea (FN)', 'https://escudosfc.com.br/images/chelsea_fn.png', 26, 17),
('CIT', 'https://escudosfc.com.br/images/cit_pe.png', 26, 17),
('Colligação', 'https://escudosfc.com.br/images/pe_coligacao.png', 26, 17),
('Colombo', 'https://escudosfc.com.br/images/colombo_pe.png', 26, 17),
('Comercial (Pesqueira)', 'https://escudosfc.com.br/images/comercial_pesq_pe.png', 26, 17),
('Comercial (Serra Talhada)', 'https://escudosfc.com.br/images/pe_comercial.gif', 26, 17),
('Comércio', 'https://escudosfc.com.br/images/comercio_pe.gif', 26, 17),
('Condor', 'https://escudosfc.com.br/images/condor_pe.png', 26, 17),
('Conceição', 'https://escudosfc.com.br/images/conceicao_fern.jpg', 26, 17),
('Cruzeiro (Água Preta)', 'https://escudosfc.com.br/images/pe_cruzeiro.png', 26, 17),
('Cruzeiro (Paudalho)', 'https://escudosfc.com.br/images/cruzeiro_paudalho_pe.png', 26, 17),
('Cruzeiro (Pesqueira)', 'https://escudosfc.com.br/images/cruzeiro_pesq_pe.png', 26, 17),
('Cucaú', 'https://escudosfc.com.br/images/cucau_pe.png', 26, 17),
('Cultura', 'https://escudosfc.com.br/images/cultura_pe.png', 26, 17),
-- D-F
('Democrático', 'https://escudosfc.com.br/images/democartico_pe.png', 26, 17),
('Destilaria', 'https://escudosfc.com.br/images/destilaria_pe.png', 26, 17),
('DR-5', 'https://escudosfc.com.br/images/dr5_pe.png', 26, 17),
('Egipciense', 'https://escudosfc.com.br/images/pe_egipciense.jpg', 26, 17),
('Elmo', 'https://escudosfc.com.br/images/pe_elmo.jpg', 26, 17),
('Encruzilhada', 'https://escudosfc.com.br/images/pe_encruzilhada.png', 26, 17),
('Equador', 'https://escudosfc.com.br/images/pe_equador.jpg', 26, 17),
('Espinheiro', 'https://escudosfc.com.br/images/espinheiro_pe.png', 26, 17),
('Estrela', 'https://escudosfc.com.br/images/estrela_pe.jpg', 26, 17),
('Estudantes (Recife)', 'https://escudosfc.com.br/images/pe_estudantes.jpg', 26, 17),
('Estudantes (Timbaúba)', 'https://escudosfc.com.br/images/estudantes_pe.gif', 26, 17),
('Eutrópio Freire', 'https://escudosfc.com.br/images/eutopio_pe.png', 26, 17),
('Expressinho', 'https://escudosfc.com.br/images/expressinho_pe.png', 26, 17),
('FAB', 'https://escudosfc.com.br/images/forca_aerea_fer.png', 26, 17),
('Fábrica Yolanda', 'https://escudosfc.com.br/images/yolanda_pe.png', 26, 17),
('Ferroviário (Cabo)', 'https://escudosfc.com.br/images/ferroviario_cabo.png', 26, 17),
('Ferroviário (Recife)', 'https://escudosfc.com.br/images/ferroviario_pe.gif', 26, 17),
('Ferroviário (Serra Talhada)', 'https://escudosfc.com.br/images/ferroviariost.gif', 26, 17),
('Flamengo (Arcoverde)', 'https://escudosfc.com.br/images/flamengo_pe.png', 26, 17),
('Flamengo (Barreiros)', 'https://escudosfc.com.br/images/flamengo_barreiros_pe.png', 26, 17),
('Flamengo FC', 'https://escudosfc.com.br/images/flamengo_recife_pe.png', 26, 17),
('Flamengo SC', 'https://escudosfc.com.br/images/flamengo_re_pe.png', 26, 17),
('Fluminense', 'https://escudosfc.com.br/images/pe_flu.png', 26, 17),
-- G-L
('Gameleira', 'https://escudosfc.com.br/images/gamaleira_pe.png', 26, 17),
('Gimnasia', 'https://escudosfc.com.br/images/gimnsaia_fer.png', 26, 17),
('Globo', 'https://escudosfc.com.br/images/globo_pe.png', 26, 17),
('Gravataense', 'https://escudosfc.com.br/images/gravataense_pe.jpg', 26, 17),
('Great Western', 'https://escudosfc.com.br/images/great_west_pe.png', 26, 17),
('Grêmio (FN)', 'https://escudosfc.com.br/images/gremio_fn.png', 26, 17),
('Grêmio Belenenses', 'https://escudosfc.com.br/images/gremio_belem_pe.png', 26, 17),
('Grêmio Lítero', 'https://escudosfc.com.br/images/pe_gremiosnaharo.png', 26, 17),
('Grêmio São José', 'https://escudosfc.com.br/images/gremio_sj_pe.png', 26, 17),
('Guarani (Alagoinha)', 'https://escudosfc.com.br/images/pe_guarani.jpg', 26, 17),
('Guarani (Jaboatão)', 'https://escudosfc.com.br/images/guarani_pe.png', 26, 17),
('Guarani (Tracunhaém)', 'https://escudosfc.com.br/images/pe_guarani_tra.png', 26, 17),
('Guarany', 'https://escudosfc.com.br/images/guarany_pe.png', 26, 17),
('Ibis', 'https://escudosfc.com.br/images/ibis_pe.jpg', 26, 17),
('Independente (Garanhuns)', 'https://escudosfc.com.br/images/indep_gara_pe.png', 26, 17),
('Independente (Pesqueira)', 'https://escudosfc.com.br/images/indep_pesq_pe.png', 26, 17),
('Intercontinental', 'https://escudosfc.com.br/images/intercontinental_pe.gif', 26, 17),
('Ipiranga (Toritama)', 'https://escudosfc.com.br/images/ipiranga_toritama_pe.png', 26, 17),
('Ipojuca FC', 'https://escudosfc.com.br/images/ipojuca_fc.png', 26, 17),
('Iporanga', 'https://escudosfc.com.br/images/iporanga_pe.png', 26, 17),
('Íris', 'https://escudosfc.com.br/images/pe_iris.jpg', 26, 17),
('Israelita', 'https://escudosfc.com.br/images/pe_israelita.png', 26, 17),
('Itacurubá', 'https://escudosfc.com.br/images/itacuruba_pe.jpg', 26, 17),
('JET', 'https://escudosfc.com.br/images/jet_pe.png', 26, 17),
('João de Barros', 'https://escudosfc.com.br/images/joao_barros_pe.png', 26, 17),
('Lagodourense', 'https://escudosfc.com.br/images/lagodourense_pe.jpg', 26, 17),
('Leão XIII', 'https://escudosfc.com.br/images/pe_leao.png', 26, 17),
('Livramento', 'https://escudosfc.com.br/images/livramento_pe.png', 26, 17),
('Locomoção', 'https://escudosfc.com.br/images/locomocao_pe.png', 26, 17),
-- M-P
('Manchete', 'https://escudosfc.com.br/images/manchete_pe.png', 26, 17),
('Maravilha', 'https://escudosfc.com.br/images/maravilha_fn.png', 26, 17),
('Maravilhas', 'https://escudosfc.com.br/images/maravilhas_pe.png', 26, 17),
('Marília', 'https://escudosfc.com.br/images/marila_pe.png', 26, 17),
('Moinho Recife', 'https://escudosfc.com.br/images/pe_moinho.jpg', 26, 17),
('Monte Castelo', 'https://escudosfc.com.br/images/montecastelo_pe.png', 26, 17),
('Nacional (Belo Jardim)', 'https://escudosfc.com.br/images/nacional_bj_pe.png', 26, 17),
('Nacional (Carpina)', 'https://escudosfc.com.br/images/nacional_carpina_pe.jpg', 26, 17)
ON CONFLICT DO NOTHING;