-- Inserir times de São Paulo (estado_id: 25, pais_id: 26)
INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- Série A1
('Botafogo SP', 'https://escudosfc.com.br/images/botasp.png', 26, 25),
('Capivariano', 'https://escudosfc.com.br/images/capivariano.gif', 26, 25),
('Corinthians', 'https://escudosfc.com.br/images/corinthians.png', 26, 25),
('Grêmio Novorizontino', 'https://escudosfc.com.br/images/novorizontino_novo.jpg', 26, 25),
('Guarani', 'https://escudosfc.com.br/images/guarani.gif', 26, 25),
('Mirassol', 'https://escudosfc.com.br/images/mirassol.jpg', 26, 25),
('Noroeste', 'https://escudosfc.com.br/images/noroeste.png', 26, 25),
('Palmeiras', 'https://escudosfc.com.br/images/palmeiras.png', 26, 25),
('Ponte Preta', 'https://escudosfc.com.br/images/pontepreta.gif', 26, 25),
('Portuguesa', 'https://escudosfc.com.br/images/portuguesa.png', 26, 25),
('Primavera', 'https://escudosfc.com.br/images/primavera_sp.png', 26, 25),
('Red Bull Bragantino', 'https://escudosfc.com.br/images/bragantino.png', 26, 25),
('Santos', 'https://escudosfc.com.br/images/santos.png', 26, 25),
('São Bernardo', 'https://escudosfc.com.br/images/sao_bernarndo_sp.png', 26, 25),
('São Paulo', 'https://escudosfc.com.br/images/saopaulo.png', 26, 25),
('Velo Clube', 'https://escudosfc.com.br/images/veloclube.png', 26, 25),
-- Série A2
('Água Santa', 'https://escudosfc.com.br/images/agua_santa_sp.png', 26, 25),
('Ferroviária', 'https://escudosfc.com.br/images/ferroviaria.png', 26, 25),
('Grêmio Prudente', 'https://escudosfc.com.br/images/gremio_prudente_novo_sp.jpg', 26, 25),
('Internacional Limeira', 'https://escudosfc.com.br/images/intl.png', 26, 25),
('Ituano', 'https://escudosfc.com.br/images/ituano.png', 26, 25),
('Juventus SP', 'https://escudosfc.com.br/images/juventus1.gif', 26, 25),
('Linense', 'https://escudosfc.com.br/images/linense.jpg', 26, 25),
('Monte Azul', 'https://escudosfc.com.br/images/monteazul.png', 26, 25),
('Osasco Sporting', 'https://escudosfc.com.br/images/osascooeste_sp.png', 26, 25),
('Santo André', 'https://escudosfc.com.br/images/santo_andre.png', 26, 25),
('São Bento SP', 'https://escudosfc.com.br/images/sao_bento.png', 26, 25),
('São José SP', 'https://escudosfc.com.br/images/sao_jose.png', 26, 25),
('Sertãozinho', 'https://escudosfc.com.br/images/sertaozinho.png', 26, 25),
('Taubaté', 'https://escudosfc.com.br/images/taubate.png', 26, 25),
('Votuporanguense', 'https://escudosfc.com.br/images/votuporanguense_sp.png', 26, 25),
('XV de Piracicaba', 'https://escudosfc.com.br/images/xv.png', 26, 25),
-- Série A3
('Bandeirante SP', 'https://escudosfc.com.br/images/bandeirante.png', 26, 25),
('Catanduvense', 'https://escudosfc.com.br/images/catanduvafc_sp.png', 26, 25),
('Desportivo Brasil', 'https://escudosfc.com.br/images/desp_brasil_sp.png', 26, 25),
('EC São Bernardo', 'https://escudosfc.com.br/images/ex_sao_bernardo.jpg', 26, 25),
('Francana', 'https://escudosfc.com.br/images/francana.png', 26, 25),
('Itapirense', 'https://escudosfc.com.br/images/itapirense.png', 26, 25),
('Marília', 'https://escudosfc.com.br/images/marilia.png', 26, 25),
('Paulista Jundiaí', 'https://escudosfc.com.br/images/paulista_sp.jpg', 26, 25),
('Portuguesa Santista', 'https://escudosfc.com.br/images/portsan.gif', 26, 25),
('Rio Branco SP', 'https://escudosfc.com.br/images/riobrancosp.gif', 26, 25),
('Rio Claro', 'https://escudosfc.com.br/images/rioclaro.png', 26, 25),
('Rio Preto', 'https://escudosfc.com.br/images/rio_preto.png', 26, 25),
('União Barbarense', 'https://escudosfc.com.br/images/barbarense.gif', 26, 25),
('União São João', 'https://escudosfc.com.br/images/uniaosj.png', 26, 25),
('União Suzano', 'https://escudosfc.com.br/images/uniaosuzano.jpg', 26, 25),
('XV de Jaú', 'https://escudosfc.com.br/images/xv_jau.png', 26, 25),
-- Série A4
('Araçatuba', 'https://escudosfc.com.br/images/aracatuba.png', 26, 25),
('Barretos', 'https://escudosfc.com.br/images/barretos.png', 26, 25),
('Colorado SP', 'https://escudosfc.com.br/images/colorado_sp.png', 26, 25),
('Comercial SP', 'https://escudosfc.com.br/images/comercialsp.png', 26, 25),
('ECUS', 'https://escudosfc.com.br/images/ecus.png', 26, 25),
('Inter Bebedouro', 'https://escudosfc.com.br/images/interbebe.png', 26, 25),
('Jabaquara', 'https://escudosfc.com.br/images/jabaquara.png', 26, 25),
('Joseense', 'https://escudosfc.com.br/images/joseense_sp.jpg', 26, 25),
('Lemense', 'https://escudosfc.com.br/images/lemense.png', 26, 25),
('Nacional SP', 'https://escudosfc.com.br/images/nacional.png', 26, 25),
('Penapolense', 'https://escudosfc.com.br/images/penapolense_sp.png', 26, 25),
('São Caetano', 'https://escudosfc.com.br/images/sao_caetano.png', 26, 25),
('Sãocarlense', 'https://escudosfc.com.br/images/saocarlense.png', 26, 25),
('Tanabi', 'https://escudosfc.com.br/images/tanabi.png', 26, 25),
('Taquaritinga', 'https://escudosfc.com.br/images/taquaritinga.png', 26, 25),
('VOCEM', 'https://escudosfc.com.br/images/vocem_sp.png', 26, 25)
ON CONFLICT DO NOTHING;

-- Inserir times do Rio de Janeiro (estado_id: 19, pais_id: 26)
INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- Série A1
('Bangu', 'https://escudosfc.com.br/images/bangu.png', 26, 19),
('Fluminense', 'https://escudosfc.com.br/images/fluminense.png', 26, 19),
('Portuguesa RJ', 'https://escudosfc.com.br/images/portuguesa_rj.png', 26, 19),
('Sampaio Correa RJ', 'https://escudosfc.com.br/images/sampaio_correa_rj.png', 26, 19),
('Vasco da Gama', 'https://escudosfc.com.br/images/vasco.png', 26, 19),
('Volta Redonda', 'https://escudosfc.com.br/images/volta.png', 26, 19),
('Boavista RJ', 'https://escudosfc.com.br/images/boavista_rj.png', 26, 19),
('Botafogo', 'https://escudosfc.com.br/images/botafogo.gif', 26, 19),
('Flamengo', 'https://escudosfc.com.br/images/fla.png', 26, 19),
('Madureira', 'https://escudosfc.com.br/images/madureira.jpg', 26, 19),
('Maricá', 'https://escudosfc.com.br/images/marica_rj.png', 26, 19),
('Nova Iguaçu', 'https://escudosfc.com.br/images/novaiguacu_rj.jpg', 26, 19),
-- Série A2
('America RJ', 'https://escudosfc.com.br/images/america_rj.gif', 26, 19),
('Americano RJ', 'https://escudosfc.com.br/images/americano.gif', 26, 19),
('Araruama', 'https://escudosfc.com.br/images/araruama_rj.png', 26, 19),
('Audax RJ', 'https://escudosfc.com.br/images/audax_rj.png', 26, 19),
('Bonsucesso', 'https://escudosfc.com.br/images/bonsucesso.gif', 26, 19),
('Cabofriense', 'https://escudosfc.com.br/images/cabofrio.png', 26, 19),
('Olaria', 'https://escudosfc.com.br/images/olaria.png', 26, 19),
('Pérolas Negras', 'https://escudosfc.com.br/images/perolas_negras_rj.png', 26, 19),
('Resende', 'https://escudosfc.com.br/images/resende_rj.jpg', 26, 19),
('São Gonçalo EC', 'https://escudosfc.com.br/images/sao_goncalo_ec_rj.png', 26, 19),
('Serrano RJ', 'https://escudosfc.com.br/images/serrano_rj.jpg', 26, 19),
-- Série B1
('Campo Grande', 'https://escudosfc.com.br/images/campogrande.gif', 26, 19),
('Carapebus', 'https://escudosfc.com.br/images/carapebus_rj.png', 26, 19),
('Duque de Caxias', 'https://escudosfc.com.br/images/duquedecaxias.png', 26, 19),
('Goytacaz', 'https://escudosfc.com.br/images/goytacaz.gif', 26, 19),
('Macaé', 'https://escudosfc.com.br/images/macae_rj.jpg', 26, 19),
('Niteroiense', 'https://escudosfc.com.br/images/niteroinese_rj.png', 26, 19),
('Nova Cidade', 'https://escudosfc.com.br/images/nova_cidade_rj.png', 26, 19),
('Petrópolis FC', 'https://escudosfc.com.br/images/petropolis_fc_rj.png', 26, 19),
('São Cristovão', 'https://escudosfc.com.br/images/saocristovao.png', 26, 19),
('Univassouras Artsul', 'https://escudosfc.com.br/images/artsul_rj.png', 26, 19),
-- Série B2
('Friburguense', 'https://escudosfc.com.br/images/friburguense.png', 26, 19),
('Paduano', 'https://escudosfc.com.br/images/paduano_rj.gif', 26, 19),
('Santa Cruz RJ', 'https://escudosfc.com.br/images/santa_cruz_rj.png', 26, 19),
('Serra Macaense', 'https://escudosfc.com.br/images/serra_macaense_rj.png', 26, 19),
-- Série C
('Angra dos Reis', 'https://escudosfc.com.br/images/angradosreis.jpg', 26, 19),
('Barcelona RJ', 'https://escudosfc.com.br/images/barcelona_rj.jpg', 26, 19),
('Barra Mansa', 'https://escudosfc.com.br/images/barra_mansa_rj.gif', 26, 19),
('Búzios', 'https://escudosfc.com.br/images/buzios_rj.gif', 26, 19),
('Juventus RJ', 'https://escudosfc.com.br/images/juventus_rj.jpg', 26, 19),
('Mesquita', 'https://escudosfc.com.br/images/mesquita_rj.png', 26, 19)
ON CONFLICT DO NOTHING;

-- Inserir times da Bahia (estado_id: 5, pais_id: 26)
INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- Primeira Divisão
('Atlético BA', 'https://escudosfc.com.br/images/atletico_ba.png', 26, 5),
('Bahia', 'https://escudosfc.com.br/images/bahia.png', 26, 5),
('Bahia de Feira', 'https://escudosfc.com.br/images/bahiadefeira.png', 26, 5),
('Barcelona Ilhéus', 'https://escudosfc.com.br/images/barcelona_ilheus_ba.png', 26, 5),
('Galicia BA', 'https://escudosfc.com.br/images/galicia_ba.png', 26, 5),
('Jacuipense', 'https://escudosfc.com.br/images/jacuipense_ba.jpg', 26, 5),
('Jequié', 'https://escudosfc.com.br/images/jequie_ba.png', 26, 5),
('Juazeirense', 'https://escudosfc.com.br/images/juazeirense_ba.png', 26, 5),
('Porto BA', 'https://escudosfc.com.br/images/porto_ba.png', 26, 5),
('Vitória', 'https://escudosfc.com.br/images/vitoria.png', 26, 5),
-- Segunda Divisão
('Colo Colo BA', 'https://escudosfc.com.br/images/colocolo_ba.png', 26, 5),
('Fluminense BA', 'https://escudosfc.com.br/images/flu_ba.gif', 26, 5),
('Grapiúna', 'https://escudosfc.com.br/images/ba_grapiuna.jpg', 26, 5),
('Itabuna', 'https://escudosfc.com.br/images/itabuna.png', 26, 5),
('Jacobina', 'https://escudosfc.com.br/images/jacobina_ba.gif', 26, 5),
('Leônico', 'https://escudosfc.com.br/images/leonico.png', 26, 5),
('Portela Teixeira de Freitas', 'https://escudosfc.com.br/images/teixeira_ba.png', 26, 5),
('Primeiro Passo', 'https://escudosfc.com.br/images/primeiro_passo_ba.jpg', 26, 5),
('SSA', 'https://escudosfc.com.br/images/ssa_ba.png', 26, 5),
('Ypiranga BA', 'https://escudosfc.com.br/images/ypiranga_ba.gif', 26, 5),
-- Outros
('AAB', 'https://escudosfc.com.br/images/aab_ba.png', 26, 5),
('ABB', 'https://escudosfc.com.br/images/abb_ba.png', 26, 5),
('Catuense', 'https://escudosfc.com.br/images/catuense.png', 26, 5),
('Conquista EC', 'https://escudosfc.com.br/images/conquista.jpg', 26, 5),
('Barreiras', 'https://escudosfc.com.br/images/barreiras_ba.png', 26, 5),
('UNIRB', 'https://escudosfc.com.br/images/unirb_ba.png', 26, 5)
ON CONFLICT DO NOTHING;