-- Insert Pernambuco teams (estado_id = 17, pais_id = 26)
INSERT INTO public.times (nome, escudo_url, estado_id, pais_id) VALUES
('Decisão', 'https://escudosfc.com.br/images/decisao_pe.png', 17, 26),
('Jaguar', 'https://escudosfc.com.br/images/jaguar_pe.jpg', 17, 26),
('Maguary', 'https://escudosfc.com.br/images/pe_maguary.png', 17, 26),
('Náutico', 'https://escudosfc.com.br/images/nautico.png', 17, 26),
('Retrô', 'https://escudosfc.com.br/images/retro_pe.png', 17, 26),
('Santa Cruz', 'https://escudosfc.com.br/images/santacruz.png', 17, 26),
('Sport', 'https://escudosfc.com.br/images/sport.gif', 17, 26),
('Vitória das Tabocas', 'https://escudosfc.com.br/images/vitoria_pe.jpg', 17, 26),
('Afogados', 'https://escudosfc.com.br/images/afogados_pe.jpg', 17, 26),
('Águia de Marabá', 'https://escudosfc.com.br/images/aguia_pe.jpg', 17, 26),
('América', 'https://escudosfc.com.br/images/america_pe.png', 17, 26),
('Belo Jardim', 'https://escudosfc.com.br/images/belojardim.png', 17, 26),
('Central', 'https://escudosfc.com.br/images/central_pe.png', 17, 26),
('Petrolina', 'https://escudosfc.com.br/images/petrolina.png', 17, 26),
('Salgueiro', 'https://escudosfc.com.br/images/salgueiro_pe.png', 17, 26),
('Serra Talhada', 'https://escudosfc.com.br/images/serratalhada.png', 17, 26),
('Flamengo de Arcoverde', 'https://escudosfc.com.br/images/flamengo_pe.png', 17, 26),
('Íbis', 'https://escudosfc.com.br/images/ibis.png', 17, 26),
('Caruaru City', 'https://escudosfc.com.br/images/caruarucity.png', 17, 26),
('Vera Cruz', 'https://escudosfc.com.br/images/veracruz_pe.png', 17, 26),
('Porto', 'https://escudosfc.com.br/images/porto_pe.png', 17, 26),
('Sete de Setembro', 'https://escudosfc.com.br/images/setedesetembro_pe.png', 17, 26),
('Cabense', 'https://escudosfc.com.br/images/cabense.png', 17, 26),
('1º de Maio', 'https://escudosfc.com.br/images/1demaio_pe.jpg', 17, 26),
('Atlético Pernambucano', 'https://escudosfc.com.br/images/atletico_pe.png', 17, 26),
('Auto Esporte', 'https://escudosfc.com.br/images/autoesporte_pe.png', 17, 26),
('Barreiros', 'https://escudosfc.com.br/images/barreiros_pe.png', 17, 26),
('Canaã', 'https://escudosfc.com.br/images/canaa_pe.png', 17, 26),
('Ferroviário', 'https://escudosfc.com.br/images/ferroviario_pe.png', 17, 26),
('Guarani', 'https://escudosfc.com.br/images/guarani_pe.png', 17, 26),
('Internacional', 'https://escudosfc.com.br/images/internacional_pe.png', 17, 26),
('Jaboatão', 'https://escudosfc.com.br/images/jaboatao.png', 17, 26),
('Paulistano', 'https://escudosfc.com.br/images/paulistano_pe.png', 17, 26),
('Santa Maria', 'https://escudosfc.com.br/images/santamaria_pe.png', 17, 26),
('São Paulo do Recife', 'https://escudosfc.com.br/images/saopaulo_pe.png', 17, 26),
('Torre', 'https://escudosfc.com.br/images/torre_pe.png', 17, 26),
('Tramways', 'https://escudosfc.com.br/images/tramways_pe.png', 17, 26),
('América de Vitória', 'https://escudosfc.com.br/images/americavitoria_pe.png', 17, 26),
('Araripina', 'https://escudosfc.com.br/images/araripina.png', 17, 26),
('Arcoverde', 'https://escudosfc.com.br/images/arcoverde.png', 17, 26),
('Atlético Caruaru', 'https://escudosfc.com.br/images/atleticocaruaru.png', 17, 26),
('Atlético Gravatá', 'https://escudosfc.com.br/images/atleticogravata.png', 17, 26),
('Bonito', 'https://escudosfc.com.br/images/bonito_pe.png', 17, 26),
('Camaragibe', 'https://escudosfc.com.br/images/camaragibe.png', 17, 26),
('Capibaribe', 'https://escudosfc.com.br/images/capibaribe.png', 17, 26),
('Comercial', 'https://escudosfc.com.br/images/comercial_pe.png', 17, 26),
('Coruripe de Paulista', 'https://escudosfc.com.br/images/coruripe_pe.png', 17, 26),
('Desportivo', 'https://escudosfc.com.br/images/desportivo_pe.png', 17, 26),
('Escada', 'https://escudosfc.com.br/images/escada.png', 17, 26),
('Floresta', 'https://escudosfc.com.br/images/floresta_pe.png', 17, 26),
('Garanhuns', 'https://escudosfc.com.br/images/garanhuns.png', 17, 26),
('Ipsep', 'https://escudosfc.com.br/images/ipsep.png', 17, 26),
('Igarassu', 'https://escudosfc.com.br/images/igarassu.png', 17, 26),
('Olinda', 'https://escudosfc.com.br/images/olinda.png', 17, 26),
('Palmeiras de Goiana', 'https://escudosfc.com.br/images/palmeiras_pe.png', 17, 26),
('Pesqueira', 'https://escudosfc.com.br/images/pesqueira.png', 17, 26),
('Recife', 'https://escudosfc.com.br/images/recife.png', 17, 26),
('River', 'https://escudosfc.com.br/images/river_pe.png', 17, 26),
('Serrano de Garanhuns', 'https://escudosfc.com.br/images/serrano_pe.png', 17, 26),
('Timbaúba', 'https://escudosfc.com.br/images/timbauba.png', 17, 26),
('Tuna Luso', 'https://escudosfc.com.br/images/tunaluso_pe.png', 17, 26),
('União', 'https://escudosfc.com.br/images/uniao_pe.png', 17, 26),
('Vitória de Santo Antão', 'https://escudosfc.com.br/images/vitoriasantoantao.png', 17, 26)
ON CONFLICT DO NOTHING;