-- Adicionar mais times de Pernambuco que ainda faltam (Lote 7)
INSERT INTO times (nome, escudo_url, estado_id, pais_id) VALUES
('Águas Belas', 'https://escudosfc.com.br/pe/aguasbelas.png', 17, 1),
('América de Jaboatão', 'https://escudosfc.com.br/pe/americajaboatao.png', 17, 1),
('Atlético de Pernambuco', 'https://escudosfc.com.br/pe/atleticope.png', 17, 1),
('Bezerros', 'https://escudosfc.com.br/pe/bezerros.png', 17, 1),
('Bonito', 'https://escudosfc.com.br/pe/bonito.png', 17, 1),
('Cabense', 'https://escudosfc.com.br/pe/cabense.png', 17, 1),
('Caetés', 'https://escudosfc.com.br/pe/caetes.png', 17, 1),
('Camorim', 'https://escudosfc.com.br/pe/camorim.png', 17, 1),
('Capibaribe', 'https://escudosfc.com.br/pe/capibaribe.png', 17, 1),
('Caruaru City', 'https://escudosfc.com.br/pe/caruarucity.png', 17, 1),
('Comunicações', 'https://escudosfc.com.br/pe/comunicacoes.png', 17, 1),
('Destaque', 'https://escudosfc.com.br/pe/destaque.png', 17, 1),
('Exú', 'https://escudosfc.com.br/pe/exu.png', 17, 1),
('Floresta', 'https://escudosfc.com.br/pe/florestape.png', 17, 1),
('Fluminense de Recife', 'https://escudosfc.com.br/pe/fluminenserecife.png', 17, 1),
('Goiana', 'https://escudosfc.com.br/pe/goianape.png', 17, 1),
('Gravatá', 'https://escudosfc.com.br/pe/gravata.png', 17, 1),
('Itamaracá', 'https://escudosfc.com.br/pe/itamaraca.png', 17, 1),
('Jaboatão', 'https://escudosfc.com.br/pe/jaboatao.png', 17, 1),
('Limoeiro', 'https://escudosfc.com.br/pe/limoeiro.png', 17, 1),
('Macaparana', 'https://escudosfc.com.br/pe/macaparana.png', 17, 1),
('Moreno', 'https://escudosfc.com.br/pe/moreno.png', 17, 1),
('Oratório', 'https://escudosfc.com.br/pe/oratorio.png', 17, 1),
('Ouricuri', 'https://escudosfc.com.br/pe/ouricuri.png', 17, 1),
('Pernambucano', 'https://escudosfc.com.br/pe/pernambucano.png', 17, 1),
('Petribu', 'https://escudosfc.com.br/pe/petribu.png', 17, 1),
('Pontual', 'https://escudosfc.com.br/pe/pontual.png', 17, 1),
('Quipapá', 'https://escudosfc.com.br/pe/quipapa.png', 17, 1),
('Santo Amaro', 'https://escudosfc.com.br/pe/santoamaro.png', 17, 1),
('Social', 'https://escudosfc.com.br/pe/social.png', 17, 1),
('Sport Recife Sub-23', 'https://escudosfc.com.br/pe/sportsub23.png', 17, 1),
('Timbaúba', 'https://escudosfc.com.br/pe/timbauba.png', 17, 1),
('Triunfo', 'https://escudosfc.com.br/pe/triunfo.png', 17, 1),
('Tupã', 'https://escudosfc.com.br/pe/tupape.png', 17, 1),
('Tupi de Recife', 'https://escudosfc.com.br/pe/tupirecife.png', 17, 1),
('Vasco de Recife', 'https://escudosfc.com.br/pe/vascorecife.png', 17, 1),
('Vicência', 'https://escudosfc.com.br/pe/vicencia.png', 17, 1),
('Vitória de Recife', 'https://escudosfc.com.br/pe/vitoriarecife.png', 17, 1),
('XV de Novembro', 'https://escudosfc.com.br/pe/xvnovembro.png', 17, 1),
('Zumbi', 'https://escudosfc.com.br/pe/zumbi.png', 17, 1)
ON CONFLICT DO NOTHING;