
-- Adicionar times de São Paulo - Parte 1 (Séries Profissionais e Outros - A até Am)
-- Total: ~150 times

INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- Série A1 (já existentes, ON CONFLICT)
('Botafogo SP', 'https://escudosfc.com.br/images/botasp.png', 26, 25),
('Capivariano', 'https://escudosfc.com.br/images/capivariano.gif', 26, 25),
('Corinthians', 'https://escudosfc.com.br/images/corinthians.png', 26, 25),
('Grêmio Novorizontino', 'https://escudosfc.com.br/images/novorizontino_novo.jpg', 26, 25),
('Guarani', 'https://escudosfc.com.br/images/guarani.gif', 26, 25),
('Mirassol', 'https://escudosfc.com.br/images/mirassol.jpg', 26, 25),
('Noroeste', 'https://escudosfc.com.br/images/noroeste.png', 26, 25),
('Palmeiras', 'https://escudosfc.com.br/images/palmeiras.png', 26, 25),
('Ponte Preta', 'https://escudosfc.com.br/images/pontepreta.gif', 26, 25),
('Portuguesa', 'https://escudosfc.com.br/images/portuguesa.png', 26, 25),
('Primavera SP', 'https://escudosfc.com.br/images/primavera_sp.png', 26, 25),
('Red Bull Bragantino', 'https://escudosfc.com.br/images/bragantino.png', 26, 25),
('Santos', 'https://escudosfc.com.br/images/santos.png', 26, 25),
('São Bernardo FC', 'https://escudosfc.com.br/images/sao_bernarndo_sp.png', 26, 25),
('São Paulo', 'https://escudosfc.com.br/images/saopaulo.png', 26, 25),
('Velo Clube', 'https://escudosfc.com.br/images/veloclube.png', 26, 25),

-- Série A2
('Água Santa', 'https://escudosfc.com.br/images/agua_santa_sp.png', 26, 25),
('Ferroviária', 'https://escudosfc.com.br/images/ferroviaria.png', 26, 25),
('Grêmio Prudente', 'https://escudosfc.com.br/images/gremio_prudente_novo_sp.jpg', 26, 25),
('Internacional de Limeira', 'https://escudosfc.com.br/images/intl.png', 26, 25),
('Ituano', 'https://escudosfc.com.br/images/ituano.png', 26, 25),
('Juventus SP', 'https://escudosfc.com.br/images/juventus1.gif', 26, 25),
('Linense', 'https://escudosfc.com.br/images/linense.jpg', 26, 25),
('Monte Azul', 'https://escudosfc.com.br/images/monteazul.png', 26, 25),
('Osasco Sporting', 'https://escudosfc.com.br/images/osascooeste_sp.png', 26, 25),
('Santo André', 'https://escudosfc.com.br/images/santo_andre.png', 26, 25),
('São Bento', 'https://escudosfc.com.br/images/sao_bento.png', 26, 25),
('São José EC', 'https://escudosfc.com.br/images/sao_jose.png', 26, 25),
('Sertãozinho', 'https://escudosfc.com.br/images/sertaozinho.png', 26, 25),
('Taubaté', 'https://escudosfc.com.br/images/taubate.png', 26, 25),
('Votuporanguense', 'https://escudosfc.com.br/images/votuporanguense_sp.png', 26, 25),
('XV de Piracicaba', 'https://escudosfc.com.br/images/xv.png', 26, 25),

-- Série A3
('Bandeirante', 'https://escudosfc.com.br/images/bandeirante.png', 26, 25),
('Catanduva FC', 'https://escudosfc.com.br/images/catanduvafc_sp.png', 26, 25),
('Desportivo Brasil', 'https://escudosfc.com.br/images/desp_brasil_sp.png', 26, 25),
('EC São Bernardo', 'https://escudosfc.com.br/images/ex_sao_bernardo.jpg', 26, 25),
('Francana', 'https://escudosfc.com.br/images/francana.png', 26, 25),

-- Série A4
('Araçatuba AE', 'https://escudosfc.com.br/images/aracatuba.png', 26, 25),
('Barretos', 'https://escudosfc.com.br/images/barretos.png', 26, 25),
('Colorado Caieiras', 'https://escudosfc.com.br/images/colorado_sp.png', 26, 25),
('Comercial Ribeirão', 'https://escudosfc.com.br/images/comercialsp.png', 26, 25),
('ECUS', 'https://escudosfc.com.br/images/ecus.png', 26, 25),
('Inter de Bebedouro', 'https://escudosfc.com.br/images/interbebe.png', 26, 25),
('Jabaquara', 'https://escudosfc.com.br/images/jabaquara.png', 26, 25),
('Joseense', 'https://escudosfc.com.br/images/joseense_sp.jpg', 26, 25),
('Lemense FC', 'https://escudosfc.com.br/images/lemense.png', 26, 25),
('Nacional SP', 'https://escudosfc.com.br/images/nacional.png', 26, 25),
('Penapolense', 'https://escudosfc.com.br/images/penapolense_sp.png', 26, 25),
('São Caetano', 'https://escudosfc.com.br/images/sao_caetano.png', 26, 25),
('Sãocarlense', 'https://escudosfc.com.br/images/saocarlense.png', 26, 25),
('Tanabi', 'https://escudosfc.com.br/images/tanabi.png', 26, 25),
('Taquaritinga', 'https://escudosfc.com.br/images/taquaritinga.png', 26, 25),
('VOCEM', 'https://escudosfc.com.br/images/vocem_sp.png', 26, 25),

-- Segunda Divisão
('Assisense', 'https://escudosfc.com.br/images/assisense.png', 26, 25),
('Audax SP', 'https://escudosfc.com.br/images/gremio_osasco_audaxsp.png', 26, 25),
('Batatais', 'https://escudosfc.com.br/images/batatais.png', 26, 25),
('Flamengo Guarulhos', 'https://escudosfc.com.br/images/flamengogua.png', 26, 25),
('Guarulhos FC', 'https://escudosfc.com.br/images/guarulhos.png', 26, 25),
('Independente Limeira', 'https://escudosfc.com.br/images/independentelim.png', 26, 25),
('Manthiqueira', 'https://escudosfc.com.br/images/manthiqueira_sp.jpeg', 26, 25),
('Matonense', 'https://escudosfc.com.br/images/matonense.png', 26, 25),
('Mauá FC', 'https://escudosfc.com.br/images/maua_fc_sp.jpg', 26, 25),
('Mauaense', 'https://escudosfc.com.br/images/mauaense.png', 26, 25),

-- Outros - Seção 1-A
('5 de Outubro', 'https://escudosfc.com.br/images/5_outubro_sp.jpg', 26, 25),
('7 de Setembro', 'https://escudosfc.com.br/images/sete_setembro_sp.png', 26, 25),
('15 Campineiro', 'https://escudosfc.com.br/images/xvcampinas.jpg', 26, 25),
('AA Palmeiras', 'https://escudosfc.com.br/images/aapalmeiras_sp.png', 26, 25),
('Academia Futuro', 'https://escudosfc.com.br/images/futuro_sp.png', 26, 25),
('Acclimação', 'https://escudosfc.com.br/images/aclimacao_sp.png', 26, 25),
('Aclimação SA', 'https://escudosfc.com.br/images/aclimacaosa_sp.png', 26, 25),
('Adamantina AA', 'https://escudosfc.com.br/images/adamantina_aa.png', 26, 25),
('Adamantina FC', 'https://escudosfc.com.br/images/adamantina_sp.png', 26, 25),
('Água Branca', 'https://escudosfc.com.br/images/aguabranca_sp.png', 26, 25),
('Águas de Lindóia', 'https://escudosfc.com.br/images/aguas_lindoia_sp.png', 26, 25),
('Agudos', 'https://escudosfc.com.br/images/agurdos_sp.png', 26, 25),
('Al-Shabab SP', 'https://escudosfc.com.br/images/alshabab_sp.png', 26, 25),
('Albion', 'https://escudosfc.com.br/images/sp_albion.jpg', 26, 25),
('Alfa', 'https://escudosfc.com.br/images/alfa_sp.png', 26, 25),
('Aliança Carapicuiba', 'https://escudosfc.com.br/images/alianca_sp.jpg', 26, 25),
('Aliança SBC', 'https://escudosfc.com.br/images/alianca_sb_sp.png', 26, 25),
('Aliança Militar', 'https://escudosfc.com.br/images/alianca_mili_sp.png', 26, 25),
('Alliança Norte', 'https://escudosfc.com.br/images/alianca_norte_sp.png', 26, 25),
('Altinópolis', 'https://escudosfc.com.br/images/altino_sp.jpg', 26, 25),
('Alumínio', 'https://escudosfc.com.br/images/aluminio_sp.png', 26, 25),
('Alumni', 'https://escudosfc.com.br/images/sp_alumni.png', 26, 25),
('Alvi-Verde', 'https://escudosfc.com.br/images/alviverde_sp.jpg', 26, 25),
('Amália', 'https://escudosfc.com.br/images/amalia_sp.png', 26, 25),
('América Ibitinga', 'https://escudosfc.com.br/images/america_ibi_sp.jpg', 26, 25),
('América Jaú', 'https://escudosfc.com.br/images/america_jau_sp.jpg', 26, 25),
('América Rio Preto', 'https://escudosfc.com.br/images/americarp.png', 26, 25),
('América São Manuel', 'https://escudosfc.com.br/images/sp_america_saomanu.jpg', 26, 25),
('América SP', 'https://escudosfc.com.br/images/sp_america_sp.png', 26, 25),
('American Vila', 'https://escudosfc.com.br/images/american_sp.png', 26, 25),
('Americana AA', 'https://escudosfc.com.br/images/americana_sp.jpg', 26, 25),
('Americana EC', 'https://escudosfc.com.br/images/americana_ec_sp.jpg', 26, 25),
('Americano Ibitinga', 'https://escudosfc.com.br/images/americano_ibi_sp.png', 26, 25),
('Americano SP', 'https://escudosfc.com.br/images/americano_sp.gif', 26, 25),
('Américo Brasiliense', 'https://escudosfc.com.br/images/americo_sp.jpg', 26, 25),
('Amparo', 'https://escudosfc.com.br/images/amparo.jpg', 26, 25),
('Analandense', 'https://escudosfc.com.br/images/analadense_sp.png', 26, 25),
('Andradina', 'https://escudosfc.com.br/images/andradina_sp.png', 26, 25),
('Andreense', 'https://escudosfc.com.br/images/andreense_sp.png', 26, 25),
('Angatubense', 'https://escudosfc.com.br/images/angatubense_sp.png', 26, 25),
('Antarctica', 'https://escudosfc.com.br/images/sp_antarctica.png', 26, 25),
('Aparecida', 'https://escudosfc.com.br/images/aparecida_sp.png', 26, 25),
('Araçatuba EC', 'https://escudosfc.com.br/images/aracatuba_sp.png', 26, 25),
('Araçatuba FC', 'https://escudosfc.com.br/images/fc_aracatuba_sp.png', 26, 25),
('Araraquara FC', 'https://escudosfc.com.br/images/araraquara_sp.png', 26, 25)

ON CONFLICT (nome) DO NOTHING;
