-- Adicionar mais times de São Paulo da seção Outros (1-A)
INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
  ('5 de Outubro', 'https://escudosfc.com.br/images/5_outubro_sp.jpg', 26, 25),
  ('7 de Setembro', 'https://escudosfc.com.br/images/sete_setembro_sp.png', 26, 25),
  ('15 Campineiro', 'https://escudosfc.com.br/images/xvcampinas.jpg', 26, 25),
  ('AA Palmeiras', 'https://escudosfc.com.br/images/aapalmeiras_sp.png', 26, 25),
  ('Academia Futuro', 'https://escudosfc.com.br/images/futuro_sp.png', 26, 25),
  ('Acclimação', 'https://escudosfc.com.br/images/aclimacao_sp.png', 26, 25),
  ('Aclimação SA', 'https://escudosfc.com.br/images/aclimacaosa_sp.png', 26, 25),
  ('Adamantina AA', 'https://escudosfc.com.br/images/adamantina_aa.png', 26, 25),
  ('Adamantina FC', 'https://escudosfc.com.br/images/adamantina_sp.png', 26, 25),
  ('Água Branca', 'https://escudosfc.com.br/images/aguabranca_sp.png', 26, 25),
  ('Águas de Lindóia', 'https://escudosfc.com.br/images/aguas_lindoia_sp.png', 26, 25),
  ('Agudos', 'https://escudosfc.com.br/images/agurdos_sp.png', 26, 25),
  ('Al-Shabab', 'https://escudosfc.com.br/images/alshabab_sp.png', 26, 25),
  ('Albion', 'https://escudosfc.com.br/images/sp_albion.jpg', 26, 25),
  ('Alfa', 'https://escudosfc.com.br/images/alfa_sp.png', 26, 25),
  ('Aliança Carapicuíba', 'https://escudosfc.com.br/images/alianca_sp.jpg', 26, 25),
  ('Aliança São Bernardo', 'https://escudosfc.com.br/images/alianca_sb_sp.png', 26, 25),
  ('Aliança Militar', 'https://escudosfc.com.br/images/alianca_mili_sp.png', 26, 25),
  ('Alliança Norte', 'https://escudosfc.com.br/images/alianca_norte_sp.png', 26, 25),
  ('Altinópolis', 'https://escudosfc.com.br/images/altino_sp.jpg', 26, 25),
  ('Alumínio', 'https://escudosfc.com.br/images/aluminio_sp.png', 26, 25),
  ('Alumni', 'https://escudosfc.com.br/images/sp_alumni.png', 26, 25),
  ('Alvi-Verde', 'https://escudosfc.com.br/images/alviverde_sp.jpg', 26, 25),
  ('Amália', 'https://escudosfc.com.br/images/amalia_sp.png', 26, 25),
  ('América Ibitinga', 'https://escudosfc.com.br/images/america_ibi_sp.jpg', 26, 25),
  ('América Jaú', 'https://escudosfc.com.br/images/america_jau_sp.jpg', 26, 25),
  ('América Rio Preto', 'https://escudosfc.com.br/images/americarp.png', 26, 25),
  ('América São Manuel', 'https://escudosfc.com.br/images/sp_america_saomanu.jpg', 26, 25),
  ('América SP', 'https://escudosfc.com.br/images/sp_america_sp.png', 26, 25),
  ('American Vila', 'https://escudosfc.com.br/images/american_sp.png', 26, 25),
  ('Americana', 'https://escudosfc.com.br/images/americana_sp.jpg', 26, 25),
  ('Americana EC', 'https://escudosfc.com.br/images/americana_ec_sp.jpg', 26, 25),
  ('Americano Ibitinga', 'https://escudosfc.com.br/images/americano_ibi_sp.png', 26, 25),
  ('Americano SP', 'https://escudosfc.com.br/images/americano_sp.gif', 26, 25),
  ('Américo Brasiliense', 'https://escudosfc.com.br/images/americo_sp.jpg', 26, 25),
  ('Amparo', 'https://escudosfc.com.br/images/amparo.jpg', 26, 25),
  ('Analandense', 'https://escudosfc.com.br/images/analadense_sp.png', 26, 25),
  ('Andradina', 'https://escudosfc.com.br/images/andradina_sp.png', 26, 25),
  ('Andreense', 'https://escudosfc.com.br/images/andreense_sp.png', 26, 25),
  ('Angatubense', 'https://escudosfc.com.br/images/angatubense_sp.png', 26, 25),
  ('Antarctica', 'https://escudosfc.com.br/images/sp_antarctica.png', 26, 25),
  ('Aparecida', 'https://escudosfc.com.br/images/aparecida_sp.png', 26, 25),
  ('Araçatuba EC', 'https://escudosfc.com.br/images/aracatuba_sp.png', 26, 25),
  ('Araçatuba FC', 'https://escudosfc.com.br/images/fc_aracatuba_sp.png', 26, 25),
  ('Araçatuba FC (2)', 'https://escudosfc.com.br/images/aracatuba_fc_new_sp.png', 26, 25),
  -- Times da Segunda Divisão que ainda não foram adicionados
  ('Assisense', 'https://escudosfc.com.br/images/assisense.png', 26, 25),
  ('Grêmio Osasco Audax', 'https://escudosfc.com.br/images/gremio_osasco_audaxsp.png', 26, 25),
  ('Batatais', 'https://escudosfc.com.br/images/batatais.png', 26, 25),
  ('Flamengo Guarulhos', 'https://escudosfc.com.br/images/flamengogua.png', 26, 25),
  ('Guarulhos', 'https://escudosfc.com.br/images/guarulhos.png', 26, 25),
  ('Independente Limeira', 'https://escudosfc.com.br/images/independentelim.png', 26, 25),
  ('Manthiqueira', 'https://escudosfc.com.br/images/manthiqueira_sp.jpeg', 26, 25),
  ('Matonense', 'https://escudosfc.com.br/images/matonense.png', 26, 25),
  ('Mauá FC', 'https://escudosfc.com.br/images/maua_fc_sp.jpg', 26, 25),
  ('Mauaense', 'https://escudosfc.com.br/images/mauaense.png', 26, 25),
  ('Olímpia', 'https://escudosfc.com.br/images/olimpia_sp.png', 26, 25),
  ('Santacruzense', 'https://escudosfc.com.br/images/santacruzense.jpg', 26, 25),
  ('São Carlos FC', 'https://escudosfc.com.br/images/saocarlos.png', 26, 25),
  ('Tupã', 'https://escudosfc.com.br/images/tupa_sp.png', 26, 25),
  ('União Mogi', 'https://escudosfc.com.br/images/uniao_mogi.png', 26, 25),
  -- Times da Série A4 que faltavam
  ('Inter Bebedouro', 'https://escudosfc.com.br/images/interbebe.png', 26, 25)
ON CONFLICT (nome) DO NOTHING;