
-- Inserir times de Pernambuco (pais_id = 26 Brasil, estado_id = 17 Pernambuco)
-- Escudos sincronizados com https://escudosfc.com.br/images/

INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- Série A1
('Decisão', 'https://escudosfc.com.br/images/decisao_pe.png', 26, 17),
('Jaguar', 'https://escudosfc.com.br/images/jaguar_pe.jpg', 26, 17),
('Maguary', 'https://escudosfc.com.br/images/pe_maguary.png', 26, 17),
('Náutico', 'https://escudosfc.com.br/images/nautico.png', 26, 17),
('Retrô', 'https://escudosfc.com.br/images/retro_pe.png', 26, 17),
('Santa Cruz', 'https://escudosfc.com.br/images/santacruz.png', 26, 17),
('Sport', 'https://escudosfc.com.br/images/sport.gif', 26, 17),
('Vitória das Tabocas', 'https://escudosfc.com.br/images/vitoria_pe.jpg', 26, 17),
-- Série A2
('Afogados', 'https://escudosfc.com.br/images/afogados_pe.jpg', 26, 17),
('Águia', 'https://escudosfc.com.br/images/aguia_pe.jpg', 26, 17),
('América', 'https://escudosfc.com.br/images/america_pe.png', 26, 17),
('Belo Jardim', 'https://escudosfc.com.br/images/belojardim.png', 26, 17),
('Caruaru City', 'https://escudosfc.com.br/images/caruaru_city_pe.png', 26, 17),
('Central', 'https://escudosfc.com.br/images/central_pe.png', 26, 17),
('Centro Limoeirense', 'https://escudosfc.com.br/images/centro_pe.png', 26, 17),
('Ipojuca', 'https://escudosfc.com.br/images/ipojuca_pe.png', 26, 17),
('Petrolina', 'https://escudosfc.com.br/images/petrolina.png', 26, 17),
('Porto', 'https://escudosfc.com.br/images/porto_pe.png', 26, 17),
('Vera Cruz', 'https://escudosfc.com.br/images/vera_cruz_pe.jpg', 26, 17),
('Ypiranga', 'https://escudosfc.com.br/images/ypiranga_pe.png', 26, 17),
-- Outros times (1-B e amadores)
('1º de Maio', 'https://escudosfc.com.br/images/primeirodemaio_pe.png', 26, 17),
('AFASA', 'https://escudosfc.com.br/images/afasa_pe.png', 26, 17),
('Afogadense', 'https://escudosfc.com.br/images/afogadense_pe.jpg', 26, 17),
('AGA', 'https://escudosfc.com.br/images/aga_pe.png', 26, 17),
('Alegriense', 'https://escudosfc.com.br/images/alegria_pe.jpg', 26, 17),
('Altinho', 'https://escudosfc.com.br/images/altinho_pe.jpg', 26, 17),
('Alumínio', 'https://escudosfc.com.br/images/aluminio_pe.png', 26, 17),
('América de Sertânia', 'https://escudosfc.com.br/images/america_sertania_pe.png', 26, 17),
('Araripina', 'https://escudosfc.com.br/images/arapina_pe.png', 26, 17),
('Araripina SC', 'https://escudosfc.com.br/images/araripina_sc_pe.png', 26, 17),
('Arcoverde', 'https://escudosfc.com.br/images/arcoverde_pe.jpg', 26, 17),
('Arruda', 'https://escudosfc.com.br/images/pe_arruda.png', 26, 17),
('Arsenal Noronhense', 'https://escudosfc.com.br/images/arsenal_fn.png', 26, 17),
('ASA', 'https://escudosfc.com.br/images/asa_pe.png', 26, 17),
('Asa Branca', 'https://escudosfc.com.br/images/asa_branca_pe.png', 26, 17),
('Asas', 'https://escudosfc.com.br/images/pe_asas.png', 26, 17),
('Ateniense', 'https://escudosfc.com.br/images/ateniense_pe.png', 26, 17),
('Atlântico', 'https://escudosfc.com.br/images/atlantico_fn.png', 26, 17),
('Atlético de Camaragibe', 'https://escudosfc.com.br/images/ateletico_camaragibe_pe.png', 26, 17),
('Atlético Caruaru', 'https://escudosfc.com.br/images/atl_caruaru_pe.jpg', 26, 17),
('Atlético Goiana', 'https://escudosfc.com.br/images/atletic_go_pe.png', 26, 17),
('Atlético Pernambucano', 'https://escudosfc.com.br/images/atletico_pernambucano.png', 26, 17),
('Atlético Vicência', 'https://escudosfc.com.br/images/vicencia_pe.gif', 26, 17),
('Auto Esporte', 'https://escudosfc.com.br/images/pe_autoesporte.png', 26, 17),
('Barcelona', 'https://escudosfc.com.br/images/barcelona_pe.png', 26, 17),
('Barreiros AE', 'https://escudosfc.com.br/images/barreiros_ae_pe.png', 26, 17),
('Barreiros FC', 'https://escudosfc.com.br/images/barreiros_pe.png', 26, 17),
('Buíque', 'https://escudosfc.com.br/images/buique_pe.png', 26, 17),
('Cabense', 'https://escudosfc.com.br/images/cabense.jpg', 26, 17),
('Cacique', 'https://escudosfc.com.br/images/pe_cacique.jpg', 26, 17),
('Caiano CS', 'https://escudosfc.com.br/images/caiano_sc_pe.jpg', 26, 17),
('Caiano EC', 'https://escudosfc.com.br/images/caiano_ec.png', 26, 17),
('Camela', 'https://escudosfc.com.br/images/cemela_pe.png', 26, 17),
('Carpina', 'https://escudosfc.com.br/images/carpina_pe.jpg', 26, 17),
('Carpinense', 'https://escudosfc.com.br/images/carpinense_pe.jpg', 26, 17),
('Caruaru EC', 'https://escudosfc.com.br/images/pe_caruaru_ec.png', 26, 17),
('Casa Caiada', 'https://escudosfc.com.br/images/caca_caiada_pe.jpg', 26, 17),
('Casa Forte', 'https://escudosfc.com.br/images/pe_casaforte.jpg', 26, 17),
('Caxangá', 'https://escudosfc.com.br/images/caxanga_pe.png', 26, 17),
('Central Barreiros', 'https://escudosfc.com.br/images/central_barreiros_pe.png', 26, 17),
('Centro Esportivo', 'https://escudosfc.com.br/images/centro_esp_pe.png', 26, 17),
('Centro Sportivo Pernambucano', 'https://escudosfc.com.br/images/pe_csp.jpg', 26, 17),
('Chã Grande', 'https://escudosfc.com.br/images/chagrande_pe.png', 26, 17)
ON CONFLICT DO NOTHING;
