-- Inserir times adicionais de São Paulo
INSERT INTO public.times (nome, escudo_url, pais_id, estado_id) VALUES
-- Série A1
('Palmeiras', 'https://escudosfc.com.br/images/palmeiras.png', 26, 25),
('Ponte Preta', 'https://escudosfc.com.br/images/pontepreta.gif', 26, 25),
('Portuguesa', 'https://escudosfc.com.br/images/portuguesa.png', 26, 25),
('Primavera', 'https://escudosfc.com.br/images/primavera_sp.png', 26, 25),
('Red Bull Bragantino', 'https://escudosfc.com.br/images/bragantino.png', 26, 25),
('Santos', 'https://escudosfc.com.br/images/santos.png', 26, 25),
('São Bernardo', 'https://escudosfc.com.br/images/sao_bernarndo_sp.png', 26, 25),
('São Paulo', 'https://escudosfc.com.br/images/saopaulo.png', 26, 25),
('Velo Clube', 'https://escudosfc.com.br/images/veloclube.png', 26, 25),
-- Série A2
('Oeste', 'https://escudosfc.com.br/images/osascooeste_sp.png', 26, 25),
('Santo André', 'https://escudosfc.com.br/images/santo_andre.png', 26, 25),
('São Bento', 'https://escudosfc.com.br/images/sao_bento.png', 26, 25),
('São José', 'https://escudosfc.com.br/images/sao_jose.png', 26, 25),
('Sertãozinho', 'https://escudosfc.com.br/images/sertaozinho.png', 26, 25),
('Taubaté', 'https://escudosfc.com.br/images/taubate.png', 26, 25),
('Votuporanguense', 'https://escudosfc.com.br/images/votuporanguense_sp.png', 26, 25),
('XV de Piracicaba', 'https://escudosfc.com.br/images/xv.png', 26, 25),
-- Série A3
('Marília', 'https://escudosfc.com.br/images/marilia.png', 26, 25),
('Paulista', 'https://escudosfc.com.br/images/paulista_sp.jpg', 26, 25),
('Portuguesa Santista', 'https://escudosfc.com.br/images/portsan.gif', 26, 25),
('Rio Branco', 'https://escudosfc.com.br/images/riobrancosp.gif', 26, 25),
('Rio Claro', 'https://escudosfc.com.br/images/rioclaro.png', 26, 25),
('Rio Preto', 'https://escudosfc.com.br/images/rio_preto.png', 26, 25),
('União Barbarense', 'https://escudosfc.com.br/images/barbarense.gif', 26, 25),
('União São João', 'https://escudosfc.com.br/images/uniaosj.png', 26, 25),
('União Suzano', 'https://escudosfc.com.br/images/uniaosuzano.jpg', 26, 25),
('XV de Jaú', 'https://escudosfc.com.br/images/xv_jau.png', 26, 25),
-- Série A4
('Penapolense', 'https://escudosfc.com.br/images/penapolense_sp.png', 26, 25),
('São Caetano', 'https://escudosfc.com.br/images/sao_caetano.png', 26, 25),
('Sãocarlense', 'https://escudosfc.com.br/images/saocarlense.png', 26, 25),
('Tanabi', 'https://escudosfc.com.br/images/tanabi.png', 26, 25),
('Taquaritinga', 'https://escudosfc.com.br/images/taquaritinga.png', 26, 25),
('VOCEM', 'https://escudosfc.com.br/images/vocem_sp.png', 26, 25),
-- Segunda Divisão
('Assisense', 'https://escudosfc.com.br/images/assisense.png', 26, 25),
('Audax', 'https://escudosfc.com.br/images/gremio_osasco_audaxsp.png', 26, 25),
('Batatais', 'https://escudosfc.com.br/images/batatais.png', 26, 25),
('Flamengo Guarulhos', 'https://escudosfc.com.br/images/flamengogua.png', 26, 25),
('Guarulhos', 'https://escudosfc.com.br/images/guarulhos.png', 26, 25),
('Independente Limeira', 'https://escudosfc.com.br/images/independentelim.png', 26, 25),
('Manthiqueira', 'https://escudosfc.com.br/images/manthiqueira_sp.jpeg', 26, 25),
('Matonense', 'https://escudosfc.com.br/images/matonense.png', 26, 25),
('Mauá FC', 'https://escudosfc.com.br/images/maua_fc_sp.jpg', 26, 25),
('Mauaense', 'https://escudosfc.com.br/images/mauaense.png', 26, 25),
('Olímpia', 'https://escudosfc.com.br/images/olimpia_sp.png', 26, 25),
('Santacruzense', 'https://escudosfc.com.br/images/santacruzense.jpg', 26, 25),
('São Carlos', 'https://escudosfc.com.br/images/saocarlos.png', 26, 25),
('Tupã', 'https://escudosfc.com.br/images/tupa_sp.png', 26, 25),
('União Mogi', 'https://escudosfc.com.br/images/uniao_mogi.png', 26, 25),
-- Outros times tradicionais
('Fernandópolis', 'https://escudosfc.com.br/images/fernandopolis.png', 26, 25),
('Jaboticabal', 'https://escudosfc.com.br/images/jaboticabal.gif', 26, 25),
('Jacareí', 'https://escudosfc.com.br/images/jacarei.png', 26, 25),
('Guaratinguetá', 'https://escudosfc.com.br/images/guaratingueta_sp.png', 26, 25),
('Guariba', 'https://escudosfc.com.br/images/guariba.png', 26, 25),
('Guarujá', 'https://escudosfc.com.br/images/guaruja.png', 26, 25),
('Mogi Mirim', 'https://escudosfc.com.br/images/mogi.png', 26, 25),
('Atibaia', 'https://escudosfc.com.br/images/atibaia.png', 26, 25),
('Dracena', 'https://escudosfc.com.br/images/dracena_sp.gif', 26, 25),
('Grêmio Barueri', 'https://escudosfc.com.br/images/gremio_barueri_sp.png', 26, 25),
('Osasco', 'https://escudosfc.com.br/images/osasco.png', 26, 25),
('Orlândia', 'https://escudosfc.com.br/images/sp_orlandia.png', 26, 25),
('Brasilis', 'https://escudosfc.com.br/images/brasilis.png', 26, 25),
('Taboão da Serra', 'https://escudosfc.com.br/images/taboaodaserra.png', 26, 25),
('Sumaré', 'https://escudosfc.com.br/images/sumare.png', 26, 25),
('Suzano', 'https://escudosfc.com.br/images/suzano_sp.png', 26, 25)
ON CONFLICT DO NOTHING;